#!/bin/bash

SAVETPL=1
SAVEHIST=1
USEHIST=1
PLOTHIST=1

./dodjtana.sh $SAVETPL $SAVEHIST $USEHIST $PLOTHIST 0 0 0
./dodjtana.sh $SAVETPL $SAVEHIST $USEHIST $PLOTHIST 1 0 0
./dodjtana.sh $SAVETPL $SAVEHIST $USEHIST $PLOTHIST 2 0 0
./dodjtana.sh $SAVETPL $SAVEHIST $USEHIST $PLOTHIST 0 1 0
# ./dodjtana.sh $SAVETPL $SAVEHIST $USEHIST $PLOTHIST 2 0 0
