#!/bin/bash

SAVETPL=1
SAVEHIST=1
USEHIST=1
PLOTHIST=1

./dodjtana_2Dbins.sh $SAVETPL $SAVEHIST $USEHIST $PLOTHIST
./dodjtana_1Dbins.sh $SAVETPL $SAVEHIST $USEHIST $PLOTHIST

SAVERATIO=1
PLOTRATIO=1
FINALPLOT=1

./dodjtana_ratio_2Dbins.sh $SAVERATIO $PLOTRATIO $FINALPLOT
./dodjtana_ratio_1Dbins.sh $SAVERATIO $PLOTRATIO $FINALPLOT



